service: mongodb-serverless-node-rest-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    ENV_RELATIVE_PATH: ../../
  exclude:
    - config/.env.dev
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: books
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: books/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: books
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: books/{id}
          method: get

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: books/{id}
          method: delete
